# Generated by Django 4.2.25 on 2025-10-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=512, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('peer_review', models.JSONField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
